#!/usr/bin/env python3

import argparse
import os
import sys
import time
from collections import defaultdict
from pathlib import Path
from typing import Callable

import lpips
import numpy as np
import torch
from einops import rearrange
from torch.utils.data import DataLoader
from tqdm import tqdm
from transformers import AutoModelForCausalLM, default_data_collator

sys.path.append(os.getcwd())
from data import RawTokenDataset
from eval_utils import AvgMetric, decode_tokens, compute_loss_and_acc, compute_lpips
from visualize import decode_latents_wrapper

# Hardcoded values for the final dataset
WINDOW_SIZE = 16
STRIDE = 15  # Data is 30 Hz so with stride 15, video is 2 Hz
LATENT_H, LATENT_W = 20, 20  # Dimensions of the compressed image


def parse_args():
    parser = argparse.ArgumentParser(description="Evaluate a Llama-style LLM.")
    parser.add_argument(
        "--val_data_dir", type=str, default="data/val_v0",
        help="A directory with video data, should have a `metadata.json` and `video.bin`."
    )
    parser.add_argument(
        "--checkpoint_dir", type=str, default="1x-technologies/Llama_1B_v0",
        help="A directory with the model weights and config.json, or HF model."
    )
    parser.add_argument(
        "--batch_size", type=int, default=2,
        help="Batch size, current script only supports a single GPU."
    )
    parser.add_argument(
        "--save_outputs_dir", type=str,
        help="Debug option. If specified, will save model predictions and ground truths to this directory. "
             "Specifically, will save `{pred_frames,pred_logits,gtruth_frames,gtruth_tokens}.pt`"
    )
    parser.add_argument(
        "--max_examples", type=int,
        help="If specified, will stop evaluation early after `max_examples` examples."
    )

    return parser.parse_args()


class LlamaEvaluator:
    def __init__(self, checkpoint_dir: str, decode_latents: Callable, device="cuda"):
        super().__init__()
        self.model = AutoModelForCausalLM.from_pretrained(
            checkpoint_dir,
            torch_dtype=torch.bfloat16,
            attn_implementation="flash_attention_2"
        ).to(device)

        self.model.eval()

        self.decode_latents = decode_latents
        self.device = device

    def predict_zframe_logits(self, input_ids: torch.LongTensor) -> torch.Tensor:
        """
        Conditioned on previous frames: [frame_0], [frame_0, frame_1], ..., [frame_0, frame_1, ... frame_{T-1}],
        predict the tokens in the following frame: [pred_frame_1, pred_frame_2, ..., pred_frame_T].

        Image logits are auto-regressively generated across the spatial dimension (within an image) but teacher-forced
        across time dimension.

        Args:
            input_ids: LongTensor of size (B, T*H*W) corresponding to flattened, tokenized images.

        Returns:
            FloatTensor of size (B, C, T-1, H, W) corresponding to the predicted logits,
            where C=1000 is the number of classes.
        """
        input_ids = rearrange(input_ids, "b (t h w) -> b t h w", t=WINDOW_SIZE, h=LATENT_H, w=LATENT_W)

        all_logits = []
        for timestep in range(1, WINDOW_SIZE):
            prev_frames = rearrange(input_ids[:, :timestep, :, :].to(self.device), "b t h w -> b (t h w)")

            outputs = self.model.generate(
                input_ids=prev_frames, max_new_tokens=LATENT_H * LATENT_W, min_new_tokens=LATENT_H * LATENT_W,
                output_logits=True, return_dict_in_generate=True,
            )

            logits = torch.stack(outputs.logits, dim=1)
            all_logits.append(rearrange(logits, "b (h w) c -> b c h w", h=LATENT_H, w=LATENT_W))

        return torch.stack(all_logits, dim=2)

    def predict_zframe_logits_teacher(self, input_ids: torch.LongTensor) -> torch.Tensor:
        """
        Same task as `predict_zframe_logits`, except with teacher forcing.

        Returns:
            FloatTensor of size (B, C, T-1, H, W) corresponding to the predicted logits,
            where C=1000 is the number of classes.
        """

        logits = self.model(input_ids=input_ids.to(self.device)).logits  # (B, THW, C)

        shifted_logits = torch.cat([torch.zeros((logits.size(0), 1, logits.size(2)), device=self.device),
                                    logits[:, :-1, :]], dim=1)
        shifted_logits = rearrange(shifted_logits, "b (t h w) c -> b c t h w",
                                   t=WINDOW_SIZE, h=LATENT_H, w=LATENT_W)
        return shifted_logits[..., 1:, :, :]

    def predict_next_frames(self, input_ids=None, logits=None) -> torch.Tensor:
        """
        All model submissions should have this defined.

        Conditioned on each prefix: [frame_0], [frame_0, frame_1], ..., [frame_0, frame_1, ..., frame_{T-1}],
        predict the following frame: [pred_frame_1, pred_frame_2, ..., pred_frame_T].

        For this model, the frames are generated by using the argmax of `predict_zframe_logits`
        and decoding the quantized latent tokens back to the original image space.

        Args:
            input_ids: LongTensor of size (B, T*H*W) corresponding to flattened, tokenized images.
                If `logits` is not provided, will `predict_zframe_logits` using these `input_ids`.
            logits: optional FloatTensor of size (B, C, T-1, h, w).
                If `logits` has already been computed (e.g. when calculating loss),
                they can be specified here to avoid recomputation.

        Returns:
            LongTensor of size (B, T-1, 3, 160, 160) corresponding to the predicted frames.
        """
        if logits is None:
            assert input_ids is not None, "Expected at least one of `input_ids` or `logits` to be specified."
            logits = self.predict_zframe_logits(input_ids)

        top_preds = torch.argmax(logits, dim=1).cpu()
        return decode_tokens(top_preds, self.decode_latents)


@torch.no_grad()
def main():
    args = parse_args()

    val_dataset = RawTokenDataset(args.val_data_dir, window_size=WINDOW_SIZE, stride=STRIDE, filter_overlaps=True)
    decode_latents = decode_latents_wrapper(unet_checkpoint_path=val_dataset.metadata["unet"])
    lpips_alex = lpips.LPIPS(net="alex")  # Calculate LPIPS w/ AlexNet, which is the fastest model out of their options

    if args.max_examples is not None:
        val_dataset.valid_start_inds = val_dataset.valid_start_inds[:args.max_examples]

    dataloader = DataLoader(val_dataset, collate_fn=default_data_collator, batch_size=args.batch_size,)

    evaluator = LlamaEvaluator(args.checkpoint_dir, decode_latents)
    metrics = defaultdict(AvgMetric)

    if args.save_outputs_dir is not None:
        outputs_to_save = defaultdict(list)

    for i, batch in enumerate(tqdm(dataloader)):
        batch_size = batch["input_ids"].size(0)
        reshaped_input_ids = rearrange(batch["input_ids"], "b (t h w) -> b t h w", t=WINDOW_SIZE, h=LATENT_H)
        frames_per_batch = (WINDOW_SIZE - 1) * batch["input_ids"].size(0)

        start_time = time.time()
        logits = evaluator.predict_zframe_logits(batch["input_ids"])
        metrics["gen_time"].update((time.time() - start_time) / frames_per_batch, batch_size)

        if logits is not None:
            loss, acc = compute_loss_and_acc(batch["input_ids"], logits)
            metrics["loss"].update(loss, batch_size)
            metrics["acc"].update(acc, batch_size)

        start_time = time.time()
        pred_frames = evaluator.predict_next_frames(logits=logits)
        metrics["dec_time"].update((time.time() - start_time) / frames_per_batch, batch_size)

        logits_teacher = evaluator.predict_zframe_logits_teacher(batch["input_ids"])
        if logits_teacher is not None:
            loss_teacher, acc_teacher = compute_loss_and_acc(batch["input_ids"], logits_teacher)
            metrics["loss_teacher"].update(loss_teacher, batch_size)
            metrics["acc_teacher"].update(acc_teacher, batch_size)

        decoded_gtruth = decode_tokens(reshaped_input_ids, decode_latents)
        labels, prev_frames = decoded_gtruth[:, 1:], decoded_gtruth[:, :-1]
        redecoded_labels = decode_tokens(reshaped_input_ids[:, 1:], decode_latents)

        metrics["pred_lpips"].update_list(compute_lpips(labels, pred_frames, lpips_alex))
        metrics["copy_lpips"].update_list(compute_lpips(labels, prev_frames, lpips_alex))
        metrics["gtruth_lpips"].update_list(compute_lpips(labels, redecoded_labels, lpips_alex))

        print({key: val.mean() for key, val in metrics.items()})
        if args.save_outputs_dir is not None:
            outputs_to_save["pred_frames"].append(pred_frames)
            outputs_to_save["pred_logits"].append(logits)
            outputs_to_save["gtruth_frames"].append(decoded_gtruth)
            outputs_to_save["gtruth_tokens"].append(reshaped_input_ids)

    if args.save_outputs_dir is not None:
        os.makedirs(args.save_outputs_dir, exist_ok=True)
        save_outputs_dir = Path(args.save_outputs_dir)
        torch.save(torch.cat(outputs_to_save["pred_frames"], dim=0).cpu(), save_outputs_dir / "pred_frames.pt")
        torch.save(torch.cat(outputs_to_save["pred_logits"], dim=0).cpu(), save_outputs_dir / "pred_logits.pt")
        torch.save(torch.cat(outputs_to_save["gtruth_frames"], dim=0).cpu(), save_outputs_dir / "gtruth_frames.pt")
        torch.save(torch.cat(outputs_to_save["gtruth_tokens"], dim=0).cpu(), save_outputs_dir / "gtruth_tokens.pt")


if __name__ == "__main__":
    main()
